First commit
chingu-voyages/v25-geckos-team-04 pull request #16
Opened 2020-11-11 04:21 UTC by mrpeterhanley

closes #6 

Using @Material-UI/Icons for the gps target icon unless you guys have a better suggestion of how to do it

Component is used like this:

<IconButton value="&deg;C" type="main" state="on" />
<IconButton value="&deg;F" type="main" state="off" />
<IconButton type="gps" />

2020-11-11 05:20 UTC, inovux requested changes

2020-11-11 05:20 UTC, inovux commented on src/components/IconButton/index.tsx
> +    <div className={`${styles.iconbutton} ${type === 'gps'? styles.gps : null} ${state === 'on'? styles.primary : styles.secondary}`}>
Don't forget to use a `button` element :)

2020-11-11 05:20 UTC, inovux commented on src/components/IconButton/index.tsx
> +  value?: string
I dont think we need this property

2020-11-11 05:20 UTC, inovux commented on src/components/IconButton/index.tsx
> +  type: 'gps' | 'main'
Maybe you could change this to name

2020-11-11 05:20 UTC, inovux commented on src/components/IconButton/index.tsx
> +  state?: 'on' | 'off'
You can use a boolean here since its basically true | false

2020-11-11 05:20 UTC, inovux commented on src/components/IconButton/index.tsx
> +import GpsFixedIcon from '@material-ui/icons/GpsFixed';
Dont forget to install the package else the project can not build :P

2020-11-11 06:16 UTC, mrpeterhanley commented on src/components/IconButton/index.tsx
> +    <div className={`${styles.iconbutton} ${type === 'gps'? styles.gps : null} ${state === 'on'? styles.primary : styles.secondary}`}>
Done

2020-11-11 06:16 UTC, mrpeterhanley commented on src/components/IconButton/index.tsx
> +  type: 'gps' | 'main'
Done

2020-11-11 06:16 UTC, mrpeterhanley commented on src/components/IconButton/index.tsx
> +  state?: 'on' | 'off'
Done

2020-11-11 06:16 UTC, mrpeterhanley commented on src/components/IconButton/index.tsx
> +import GpsFixedIcon from '@material-ui/icons/GpsFixed';
Should be in the package.json now

2020-11-11 06:22 UTC, mrpeterhanley commented on src/components/IconButton/index.tsx
> +  value?: string
Not sure what you mean here. Do you mean don't need type checking for the value property? Or not have a value property at all?

2020-11-11 06:49 UTC, inovux commented on src/components/IconButton/index.tsx
> +  value?: string
Yeah I think we dont need the value property at all. What do you want to use it for exactly?

2020-11-11 15:08 UTC, hananina commented on src/components/IconButton/IconButton.module.css
> +  background-color: #e7e7eb; /* set to CSS variable later? */
yes I will commit this change ( adding CSS variable) later🙋🏻‍♀️

2020-11-12 01:14 UTC, inovux commented
@mrpeterhanley I merged the other branch that has the Raleway font set up. Could you update this repo to have the latest changes and add a screenshot of your component :)?

2020-11-12 05:33 UTC, mrpeterhanley commented on src/components/IconButton/index.tsx
> +  value?: string
To pass in the °C or °F text. Do you have a better suggestion for implementing this?
Since it's a reusable button I thought it's bad to limit it?

2020-11-12 06:12 UTC, mrpeterhanley commented
I updated this component with the latest changes from Develop branch and attached a screenshot also

2020-11-12 10:48 UTC, inovux approved these changes

2020-11-12 10:48 UTC, inovux commented on src/components/IconButton/index.tsx
> +  value?: string
Hmm maybe you could include it inside the name ? So have a name for Fahrenheit and Celsius as well and check for the value given to `name`.

2020-11-13 01:16 UTC, hananina commented on src/components/index.tsx
> -export { Temperature } from './Temperature'
@mrpeterhanley cc: @inovux You've rebased to the latest develop branch, so I think you shouldn't delete this line?🤔

2020-11-13 02:26 UTC, mrpeterhanley commented on src/components/IconButton/index.tsx
> +  value?: string
Good suggestion thanks! I removed it and incorporated into name as you suggested

2020-11-13 02:28 UTC, mrpeterhanley commented on src/components/IconButton/IconButton.module.css
> +  background-color: #e7e7eb; /* set to CSS variable later? */
Added the variables already, thanks

2020-11-13 02:29 UTC, mrpeterhanley commented on src/components/index.tsx
> -export { Temperature } from './Temperature'
Thanks, sorry that was my mistake...

2020-11-14 06:48 UTC, hananina requested changes
https://github.com/chingu-voyages/v25-geckos-team-04/pull/16/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR6104-R6105

Please check that there is `<<<<<<< HEAD` in this file👀?

2020-11-14 06:49 UTC, hananina commented on src/components/index.tsx
> +export { Temperature } from './Temperature'
Nice🙌🙌

2020-11-14 12:37 UTC, mrpeterhanley reviewed
Fixed, thanks

2020-11-14 12:40 UTC, hananina approved these changes
Looks good to me🙌

2020-11-14 12:46 UTC, merged