11 add weather title component
chingu-voyages/v25-geckos-team-04 pull request #17
Opened 2020-11-11 05:43 UTC by mrpeterhanley

closes #11 

The component is used like this:

`// <WeatherTitle value="Shower" />`

2020-11-11 05:47 UTC, inovux commented
Looks good to me, can you add a screenshot of your final component as well :)? I think that would be a nice last thing to add to the PR's

2020-11-12 01:15 UTC, inovux commented
Looks good to me, just update to the latest `develop` branch

2020-11-12 06:23 UTC, mrpeterhanley commented
Updated with latest changes from Develop branch and added screenshot

2020-11-12 07:50 UTC, hananina commented
@mrpeterhanley I saw this changes and it looks good! just left comments about what I notice. Please check it🙏🙏

2020-11-12 09:11 UTC, inovux requested changes

2020-11-12 09:11 UTC, inovux commented on src/components/index.tsx
> +export { WeatherTitle } from './WeatherTitle/index'
You dont need the /index here by the way

2020-11-12 09:16 UTC, inovux commented
Did you copy paste the changes from develop into your own branch? Since it seems like it shows that you made all the changes yourself somehow. If so can you actually try to rebase your branch from develop?

2020-11-12 09:52 UTC, mrpeterhanley commented
@inovux I used git checkout develop filename to add / update the new files from develop. I haven't learnt rebase yet but I will learn how to use it for next time

2020-11-12 10:49 UTC, inovux approved these changes

2020-11-12 14:57 UTC, hananina approved these changes
Looks good to me🙌🙌

2020-11-12 14:57 UTC, hananina commented on src/components/WeatherTitle/WeatherTitle.module.css
> +  color: #a09fb1;
I think you can replace #a09fb1 with css variable after merging latest develop into this branch🙋‍♀️

2020-11-12 14:57 UTC, hananina commented on src/App.tsx
> -export default App
@mrpeterhanley Can we remove this line😃? I'm ok If it's working fine🙏

2020-11-12 14:57 UTC, hananina commented on public/index.html
> +    <title>Weather App</title>
this PR seems includes changes not related to whether title component, after merging the latest develop branch😀? Is this a problem caused by the merge?

2020-11-13 02:00 UTC, merged