[WIP] #7 Add button component
chingu-voyages/v25-geckos-team-04 pull request #20
Opened 2020-11-13 15:52 UTC by hananina

WIP👩🏻‍💻

2020-11-14 08:13 UTC, mrpeterhanley approved these changes
Looks ok for me

2020-11-14 15:23 UTC, inovux requested changes

2020-11-14 15:23 UTC, inovux commented on src/components/Button/index.tsx
> +  value: string | number
Dont forget to add a `onClick` listener because its a button :)

2020-11-14 15:23 UTC, inovux commented on src/components/Button/index.tsx
> +    <>
This is not necessary because you use only one element as child which is `button`.

2020-11-14 15:23 UTC, inovux commented on src/components/Button/Button.module.css
> +  padding: 10px 18px;
you can use rems here as well: 1rem 1.8rem

2020-11-14 15:23 UTC, inovux commented on src/components/Button/Button.module.css
> +  padding: 10px 18px;
Same here :)

2020-11-14 15:25 UTC, inovux requested changes

2020-11-14 15:25 UTC, inovux commented on src/components/Button/index.tsx
> +  value: string | number
instead of using a `value` prop you can use the `children` prop, so you will use the button like this `<Button>Search</Button>` do you think this might be a better usage ?

2020-11-15 07:54 UTC, hananina commented on src/components/Button/index.tsx
> +  value: string | number
Thanks! it more practical, I will use the child prop instead🙋🏻‍♀️

2020-11-15 09:30 UTC, mrpeterhanley approved these changes
Ok for me

2020-11-15 15:15 UTC, hananina commented on src/components/Button/index.tsx
> +  value: string | number
@inovux updated with all your comments but this one...

I tried but still couldn't figure out how to set the type of the event `onclick` handles👀
how do you write usually...?🙏🙏
<img width="1061" alt="スクリーンショット 2020-11-16 0 11 18" src="https://user-images.githubusercontent.com/4989007/99188658-74a2a980-27a0-11eb-8eda-780e5516a522.png">

2020-11-16 05:20 UTC, mrpeterhanley approved these changes

2020-11-16 05:25 UTC, inovux commented on src/components/Button/index.tsx
> +  value: string | number
@hananina You can do something like this: `(event: React.MouseEvent<HTMLElement>) => void`

2020-11-17 02:03 UTC, hananina commented on src/components/Button/index.tsx
> +  value: string | number
@inovux I applied `(event: React.MouseEvent<HTMLElement>) => void`it still not working well..

I don't understand this type yet,
will check the document https://reactjs.org/docs/events.html#mouse-events and will try it later on🙋🏻‍♀️

2020-11-17 08:17 UTC, mrpeterhanley approved these changes

2020-11-17 09:30 UTC, inovux commented on src/components/Button/index.tsx
> +  value: string | number
@hananina Can I add some code to show you how it's done and push it to this branch :)?

2020-11-17 12:43 UTC, hananina commented on src/components/Button/index.tsx
> +  value: string | number
@inovux  yes🙌 it is really appreciated!

2020-11-17 12:52 UTC, inovux commented on src/components/Button/index.tsx
> +  value: string | number
@hananina Okay :) I updated it for you

2020-11-19 03:04 UTC, mrpeterhanley approved these changes

2020-11-19 04:06 UTC, hananina commented on src/components/Button/index.tsx
> +  children: React.ReactNode
📝

2020-11-19 04:14 UTC, st-currenxie approved these changes

2020-11-19 04:16 UTC, inovux approved these changes

2020-11-19 04:35 UTC, hananina commented
@inovux I added a sample button and it works!! I finally kind of got it...  Thanks for your help🙌🙌
<img width="562" alt="スクリーンショット 2020-11-19 13 29 37" src="https://user-images.githubusercontent.com/4989007/99621527-794eb280-2a6b-11eb-8a8e-f256990de285.png">

2020-11-19 04:36 UTC, merged