#12 Add current place
chingu-voyages/v25-geckos-team-04 pull request #22
Opened 2020-11-14 14:48 UTC by hananina

closes https://github.com/chingu-voyages/v25-geckos-team-04/issues/12

Added `place` property, which can be the place title

This is used like this:
```
<CurrentPlace place='hoge' />
```

<img width="83" alt="スクリーンショット 2020-11-14 23 43 45" src="https://user-images.githubusercontent.com/4989007/99149845-dea14d00-26d3-11eb-94f6-d1cf22992288.png">

2020-11-14 15:20 UTC, inovux requested changes

2020-11-14 15:20 UTC, inovux commented on src/components/CurrentPlace/index.tsx
> +        <PlaceIcon fontSize="default" />
Looking at the screenshot I feel that the Icon is too small compared to the design? Maybe you can use inherit for `fontSize` and wrap it with another element that you give a className and write a style with font size for that className. Let me know what you think :)

2020-11-14 23:31 UTC, hananina commented on src/components/CurrentPlace/index.tsx
> +        <PlaceIcon fontSize="default" />
Thanks🙏 I will check the design later😊

2020-11-15 07:45 UTC, hananina commented on src/components/CurrentPlace/index.tsx
> +        <PlaceIcon fontSize="default" />
@inovux It was smaller compare to the figma design... I updated the icon size, 15px -> 20px 👍 Thanks! 
<img width="168" alt="スクリーンショット 2020-11-15 15 58 22" src="https://user-images.githubusercontent.com/4989007/99179473-7d27bf80-2761-11eb-9b1f-d984a9fbf2b4.png">

2020-11-15 09:28 UTC, mrpeterhanley approved these changes
Ok for me

2020-11-16 09:20 UTC, inovux approved these changes
Looks good to me :)

2020-11-16 13:42 UTC, merged