#31 add wind direction component
chingu-voyages/v25-geckos-team-04 pull request #41
Opened 2020-11-19 03:00 UTC by mrpeterhanley

Takes in wind direction degrees (number) as a value since I saw that was the info provided from OpenWeatherMap API
Outputs the wind direction text (e.g. 'N', 'NNE' etc.) also rotates the icon according to the wind direction degrees

2020-11-20 01:24 UTC, inovux requested changes
Looks good to me. Just want to mention one thing, could you use `rem' instead of `px` so we keep the codebase inline :) It's basically just `0.1 * px = rem`

2020-11-20 08:46 UTC, mrpeterhanley commented
Thanks, updated values from px to rem (also for my previous components - IconButton, WeatherTitle

2020-11-21 05:22 UTC, inovux approved these changes

2020-11-21 05:29 UTC, inovux commented
@hananina @mrpeterhanley Just solved the merge conflict, should be ready to merge now when Hana approves

2020-11-21 07:58 UTC, hananina commented on src/components/WindDirection/index.tsx
> +const windDirectionValues = {
📝👀

2020-11-21 08:06 UTC, hananina approved these changes
Look good to me🎊🎊

2020-11-21 11:33 UTC, merged