#30 add Highlight Card component
chingu-voyages/v25-geckos-team-04 pull request #42
Opened 2020-11-19 05:36 UTC by mrpeterhanley

Component is used like this:
`<HighlightCard name='Air Pressure' value={998} />`
`<HighlightCard name='Humidity' value={84} />`
`<HighlightCard name='Visibility' metric='celcius' value={6400} />`
`<HighlightCard name='Wind Status' metric='celcius' value={7} windDirDeg={180} />`

For Wind Status type, it should take in two values (wind speed and wind direction in degrees)
for all other types, it takes in a single value
For Visibility, this value may need to be calculated from meters or feet to km or miles

Will add and test with sub-components (WindDirection, HumidityChart) later once merged

![Untitled](https://user-images.githubusercontent.com/67137187/99625766-e3ffee00-2a6b-11eb-8058-f1439c172b86.png)

2020-11-20 01:32 UTC, inovux requested changes
Looks good to me. Just want to mention one thing, could you use `rem' instead of `px` so we keep the codebase inline :) It's basically just `0.1 * px = rem`

2020-11-20 01:32 UTC, inovux commented on src/components/HighlightCard/index.tsx
> +
I think it would be better if we create 1 `HighLight` component that just accepts a `title` and the `metric` and from there on we create separate components for each card using the `HighLight` component as a wrapper, what do you think about that?

I think a component should not handle as many cases like this.

2020-11-20 09:02 UTC, mrpeterhanley commented on src/components/HighlightCard/index.tsx
> +
Good recommendation, I will do that now

2020-11-21 05:21 UTC, inovux requested changes

2020-11-21 05:21 UTC, inovux commented on src/components/HighlightCard/index.tsx
> +
@mrpeterhanley I think you can just check for `metric === 'fahrenheit' && name === 'Visibility'` inside the specific cards and than render anything you want inside the specific cards based on that information. So you basically handle the if statements you have here in their own cards, because for example if we have to add new cards this block of if statements will become very big, and that's something we don't want imo.

2020-11-21 11:27 UTC, mrpeterhanley commented on src/components/HighlightCard/index.tsx
> +
@inovux OK I have split the inner content of HighlightCard into four sub-components: WindStatus, Visibility, Humidity, AirPressure

2020-11-22 08:03 UTC, hananina commented on src/components/AirPressure/AirPressure.module.css
> +  line-height: 4.226rem;
@mrpeterhanley you can remove this line-height here, too👀 It probably has too much height when used with other components.

2020-11-22 08:05 UTC, hananina commented on src/components/AirPressure/AirPressure.module.css
> +  line-height: 7.514rem;
@mrpeterhanley `line-height `please remove this🙏🙏

2020-11-22 08:06 UTC, hananina approved these changes
Looks good to me🎊  I just left comments about line-height

2020-11-23 02:44 UTC, mrpeterhanley commented on src/components/AirPressure/AirPressure.module.css
> +  line-height: 4.226rem;
ok, I will remove the line-height property from all components 👌

2020-11-23 02:44 UTC, mrpeterhanley commented on src/components/AirPressure/AirPressure.module.css
> +  line-height: 7.514rem;
Ok 👌

2020-11-27 02:28 UTC, mrpeterhanley commented
Hi @inovux anything else need to change here? Otherwise I can merge this component so I can get started on the main page component

2020-11-27 03:10 UTC, inovux requested changes
@mrpeterhanley I think you can use the HighlightCard inside every component that you created here, so you don't have to wrap them every time you use them.

2020-11-27 03:21 UTC, mrpeterhanley commented
@inovux Not sure what you mean? sorry

2020-11-28 11:56 UTC, inovux commented
@mrpeterhanley Something like this:

```jsx
const VisibilityCard = () => (
<HighlightCard>
	Layout of specific card
</HighlightCard>
)
```

So basically have a card component for every card.

2020-11-29 09:09 UTC, mrpeterhanley commented
@inovux then why not just have four separate cards? I am still confused by this sorry.....maybe you can take over to help finish this issue? I am waiting it to be finished so I can implement the main page component

2020-11-29 09:29 UTC, inovux commented
@mrpeterhanley sure ill finish it for you and show you what I mean :p

2020-11-30 02:58 UTC, inovux commented
@mrpeterhanley Just added the changes let me know what you think!

2020-11-30 12:03 UTC, inovux approved these changes

2020-12-01 11:56 UTC, merged