29 Add date component
chingu-voyages/v25-geckos-team-04 pull request #45
Opened 2020-11-20 07:16 UTC by hananina

Component is used like this:
`<Date date={date} />`

Date attribute, it should take in the current date.

2020-11-20 07:28 UTC, hananina commented
@mrpeterhanley @inovux I couldn't take a screenshot because when I call this component in App.tsx, the props pass in to the date attribute seems not working...I googled it but can't figure out what is causing this problem😭
please let me know if there is a way to solve this error🙏

<img width="408" alt="スクリーンショット 2020-11-20 16 21 27" src="https://user-images.githubusercontent.com/4989007/99771419-737cce00-2b4c-11eb-9b92-314d02a72ffa.png">
<img width="506" alt="スクリーンショット 2020-11-20 16 21 15" src="https://user-images.githubusercontent.com/4989007/99771422-75df2800-2b4c-11eb-8172-d590dfcc7505.png">

2020-11-20 10:02 UTC, mrpeterhanley approved these changes
I like it

2020-11-20 10:22 UTC, mrpeterhanley commented
I think because you named your component "Date", then when you try to create a new Date(), it tries to create another copy of your component, because it is the same name as Date object

https://stackoverflow.com/questions/43744312/react-js-get-current-date/43744409

![stackoverflow](https://user-images.githubusercontent.com/67137187/99788709-741d6080-2b5c-11eb-9989-5625e2ad1124.png)

I changed your component name to "DateComponent" and it works:
![DateComponent](https://user-images.githubusercontent.com/67137187/99788810-9fa04b00-2b5c-11eb-8a98-76f5c06c44f5.png)

2020-11-20 10:28 UTC, mrpeterhanley commented
I renamed to DateComponent and fixed some errors. Please check the component now

2020-11-20 14:14 UTC, hananina commented
Oh...Name conflict was the cause of that error, It makes sense! Thank you for fixing that🙏🙏

2020-11-20 14:15 UTC, hananina commented
<img width="128" alt="スクリーンショット 2020-11-20 23 08 14" src="https://user-images.githubusercontent.com/4989007/99809853-3af9e600-2b86-11eb-8832-804df2cc0495.png">
now I can see the date on my browser😭🙌

2020-11-21 05:18 UTC, inovux requested changes

2020-11-21 05:18 UTC, inovux commented on src/components/DateComponent/index.tsx
> +  const formattedDate = format(date, 'eee d MMM')
I think we can use the format string `eee d MMM` as a property to the component called `formatString` so we can even make it more reusable. What do you think @hananina ?

2020-11-21 08:13 UTC, hananina commented on src/components/DateComponent/index.tsx
> +  const formattedDate = format(date, 'eee d MMM')
I think it's a good idea! I added the property to DateComponent🙋🏻‍♀️
<DateComponent date={new Date()} formatString='eee d MMM' />

2020-11-21 08:20 UTC, inovux approved these changes
Looks good :)

2020-11-21 08:21 UTC, merged