#34 add Highlight List component
chingu-voyages/v25-geckos-team-04 pull request #46
Opened 2020-11-20 09:55 UTC by mrpeterhanley

Component is used like this:
`<HighlightList>
        <HighlightCard name='Air Pressure' value={998} />
        <HighlightCard name='Air Pressure' value={998} />
        <HighlightCard name='Air Pressure' value={998} />
        <HighlightCard name='Air Pressure' value={998} />
</HighlightList>
`

Mobile responsive using CSS grid

![HighlightList](https://user-images.githubusercontent.com/67137187/99786534-9792dc00-2b59-11eb-8343-3da82de1243a.png)

2020-11-20 14:43 UTC, hananina commented on src/components/HighlightList/HighlightList.module.css
> +  line-height: 2.818rem;
@mrpeterhanley This line-height property seems unnecessary, we can use browser default instead  (typically '1.2' for all the major browsers)🤔?

2020-11-21 05:16 UTC, inovux requested changes
Looks good to me just 1 comment on the class name :)

2020-11-21 05:16 UTC, inovux commented on src/components/HighlightList/index.tsx
> +    <div className={styles.list__wrapper}>
Because we use CSS Modules, it's not really necessary to name your classes like this since it will be automatically generated like this. You can just call it `wrapper`.

2020-11-21 07:55 UTC, hananina approved these changes
Looks good to me🙌

2020-11-21 11:29 UTC, mrpeterhanley commented on src/components/HighlightList/HighlightList.module.css
> +  line-height: 2.818rem;
I am just copying the properties exactly from the Figma file? I am not sure if it is necessary or not but I can remove it

2020-11-21 11:29 UTC, mrpeterhanley commented on src/components/HighlightList/index.tsx
> +    <div className={styles.list__wrapper}>
Will do, thanks

2020-11-27 02:29 UTC, mrpeterhanley commented
Hi @inovux anything else need to change here? Otherwise I can merge this component so I can get started on the main page component

2020-11-27 03:10 UTC, inovux approved these changes
Looks good! 👍🏽

2020-11-27 03:17 UTC, merged