#38 add CityLink component
chingu-voyages/v25-geckos-team-04 pull request #50
Opened 2020-11-22 03:34 UTC by mrpeterhanley

Component is used like this:
`<CityLink value='Barcelona' onClick={} />`

(border and icon on hover only)

![CityLink](https://user-images.githubusercontent.com/67137187/99893039-81e6f900-2cb6-11eb-8b72-1e2b8f6f4955.png)

2020-11-22 04:59 UTC, inovux requested changes
Looks good to me just 1 comment on the property name

2020-11-22 04:59 UTC, inovux commented on src/components/CityLink/index.tsx
> +  value: string
I think it's better to call this property `city`.

2020-11-22 05:02 UTC, inovux requested changes

2020-11-22 05:02 UTC, inovux commented on src/components/CityLink/CityLink.module.css
> +  margin: 1rem 0;
I forgot this one. Margin should not be part of the component. This should be handled in a container for every item.

2020-11-22 07:50 UTC, hananina commented on src/components/CityLink/index.tsx
> +import ChevronRightIcon from '@material-ui/icons/ChevronRight'
`> `this is called Chevron👀📝

2020-11-22 07:54 UTC, hananina commented on src/components/CityLink/CityLink.module.css
> +  font-weight: 500;
font-weight: 500 = `font-weight: normal` ,It might not be necessary here🙋🏻‍♀️

2020-11-22 07:55 UTC, hananina approved these changes
Looks good to me🙌

2020-11-23 02:49 UTC, mrpeterhanley commented on src/components/CityLink/index.tsx
> +  value: string
Ok 👌

2020-11-23 02:49 UTC, mrpeterhanley commented on src/components/CityLink/CityLink.module.css
> +  margin: 1rem 0;
Ok 👌

2020-11-23 02:50 UTC, mrpeterhanley commented on src/components/CityLink/CityLink.module.css
> +  font-weight: 500;
Ok 👌

2020-11-27 03:07 UTC, inovux commented
@mrpeterhanley You gave some conflicting files.

2020-11-27 03:35 UTC, mrpeterhanley commented
@inovux I don't understand how / why these files are conflicting? They are the ones I want to merge

2020-11-27 04:53 UTC, inovux commented
@mrpeterhanley Fixed it for you, seems like the `develop` branch had those 2 files registered as deleted, so that was the conflict somehow.

2020-11-27 05:20 UTC, mrpeterhanley commented
@inovux thanks

2020-11-28 11:52 UTC, inovux approved these changes

2020-11-29 09:03 UTC, merged