#63 add metric context
chingu-voyages/v25-geckos-team-04 pull request #72
Opened 2020-12-04 09:31 UTC by mrpeterhanley

Created basic context component with useState (default is set to 'celsius') in new folder 'contexts'

2020-12-05 17:54 UTC, inovux requested changes
Dont forget to wrap it around the whole app so it can be used :)

2020-12-06 07:05 UTC, mrpeterhanley commented
@inovux done

2020-12-07 09:12 UTC, inovux approved these changes

2020-12-07 09:12 UTC, inovux commented
@mrpeterhanley dont forget to fix the conflict

2020-12-07 09:57 UTC, merged