Add weekly weather container
chingu-voyages/v25-geckos-team-04 pull request #80
Opened 2020-12-13 12:46 UTC by mrpeterhanley

2020-12-13 13:03 UTC, inovux requested changes
Using the same actions for different requests is not going to work for the `isLoading` and `hasError` states. These have to be separated for each request :)

2020-12-13 13:03 UTC, inovux commented on src/actions/weather.ts
> +  'SET_WEEKLY_WEATHER' = 'SET_WEEKLY_WEATHER',
You can not combine these in the same actions file, since the isLoading and hasErorr states are specificly used for either 1 of them. So for weekly weather you have to create a separate action file with the same action types and actions.

2020-12-14 12:35 UTC, mrpeterhanley commented on src/actions/weather.ts
> +  'SET_WEEKLY_WEATHER' = 'SET_WEEKLY_WEATHER',
Ok

2020-12-17 16:52 UTC, inovux approved these changes

2020-12-18 01:59 UTC, merged